go:
    cgo: true
repository:
    path: github.com/VoIPGRID/maxscale_exporter
build:
    binaries:
        - name: maxscale_exporter
    flags: -a -tags netgo
    ldflags: |
        -X {{repoPath}}/version.Version={{.Version}}
        -X {{repoPath}}/version.Revision={{.Revision}}
        -X {{repoPath}}/version.Branch={{.Branch}}
        -X {{repoPath}}/version.BuildUser={{user}}@{{host}}
        -X {{repoPath}}/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - darwin/amd64
        - darwin/386
        - netbsd/amd64
        - netbsd/386
        - linux/arm
        - linux/arm64
